### ISSUE TITLE
Finalize typology of entries?

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/lexicalresources#12]
We still have an unclear idea of where we want to go with the typology of entries:

> In general, the entry type can be applied locally for a single dictionary or globally to allow for classification across different dictionaries. Provided that a single dictionary will often comprise entries that describe linguistic entities of the same kind (“words”, word families, multi-word expressions, morphemes, …) a classification along those lines will be of minor importance for a stand-alone resource but may be useful in a multi-dictionary use-case. Possible values for this domain include:
> 
> - affix
> - word
> - synsetNote: e.g. for onomasiological dictionaries [Note: … though this is not the primary concern of the TEI it reads elsewhere in this text. (Laurent?)]
> - multi-word-entity
> - word-family
> 
> A classification based on macrostructural properties (i. e. properties describing aspects of the internal organisation of a resource) can on the other hand be exploited both for a single dictionary and across different dictionaries. Possible values for this domain include:
> 
> - main
> - supplemental
> - nest
> - niche
> - xr
> TODO: Priviledge one strategy (discussion)?

I don't really know what to do with this.

**Comment by ttasovac** [comment]
This is not mature enough to be implemented. We need a longer conversation. I will remove this from the 0.7.0 milestone, but I would still like to get some feedback on this.

**Comment by xlhrld** [comment]
Hm, I think I wrote your initial quote. There are two axes sketched along which types of entries could be discriminated: a) type of linguistic entity that is described in the entry and b) type of entry with regard to the structural organization of the dictionary at large.

It would generally be good to propose just one axis for TEI Lex-0 or drop `entry/@type` altogether. This would provide for a clean and straight guideline. Personally, I find axis a) a rather redundant as much (most?, all?) of this would be better recorded as `gramGrp/pos` anyway. I do not immediately see where the information regarding axis 2) could be recorded if not via `entry/@type`.

Yeah, but feedback from others on this would be most useful …

**Comment by kdepuydt** [comment]
Agree with Axel that mwe or not is better placed in a gramGrp. Indeed an entry could have different forms, one as an MWE and another as a compound (applecake vs apple cake). But still, wherever this information is located, we need a suggested terminology to use. We agree that cross reference, etc are needed because there is no other place to classify this. But do not understand niche and nest.

**Comment by anacastrosalgado** [comment]
In DACL (Dicionário da Academia das Ciências de Lisboa), a lexical unit could be:
– a Portuguese/foreign single word
– a Portuguese/foreign compound word
– an affix
– a multiword expression
– a phrase
– an abbreviation

We also have the treatment given to homonymy, homography and variation.

**Comment by anacastrosalgado** [comment]
In DACL (Dicionário da Academia das Ciências de Lisboa), a lexical unit could be:
– single word
– derivative
– compound word or fixed combination
– affix
– abbreviation

Then, we also have the treatment given to homonymy, homography and variation.

**Comment by anacastrosalgado** [comment]
From a morphological point of view, a lexical unit could be:
– single word (native or borrowed; proper name, empty word, function word)
– derivative
– compound word (native or borrowed)
– fixed combination (multiword expression, quotation, idiom, proverb, phrase)
– affix
– abbreviation (abbreviation, symbol, acronym, clipping)

Can we propose universal tags from this?
Then, we also have the treatment given to homonymy, homography and variation.

**Comment by ttasovac** [comment]
In Berlin (Jan 2019) we agreed on the following typology of entries:

- mainEntry (default)
- wordFamily
- homonymicEntry
- relatedEntry

and we dropped the "horizontal" typology. So far so good.

But the Portuguese Academy Dictionary (@anacastrosalgado), which is moving toward TEI Lex-0, would like to encode their own typology of entries:

- simpleWord
- derrivativeWord
- compoundWord
- multiWordExpression
- partialWord 
- abbreviation

The question is: how should they do it if we've blocked the use of @type for our typology?

**Comment by xlhrld** [comment]
Seems to me that these properties only apply to the `form` and not to the `entry` as a whole. At it's core, this is morphological information. So I'd argue that `entry/@type` is not the right place for this kind of information anyway.

**Comment by xlhrld** [comment]
Also: the set of values in https://github.com/DARIAH-ERIC/lexicalresources/issues/12#issuecomment-472066207 (i. e. after the meeting in January) is still strangely heterogeneous. There is no common domain to which all these values apply to. Or maybe the names are just misleading for me? Is the semantics of the `@type` values written down somewhere so we can have a look? (It's a pity I couldn't attend the morning session where this was discussed.)

**Comment by ttasovac** [comment]
Good point, @xlhrld. But the question still holds even if those are properties of the form. The type attribute is reserved for lemma, inflected and ending. Yet being able to mark up explicitly the compositional nature of the form in TEI Lex-0 is a reasonable requirement to have.

**Comment by xlhrld** [comment]
There is no canonical place for morphological information, I think. Could a solution be to reuse `pos` for this (or even better `gram[@type="partOfSpeech"]` or whatever value we agreed on)? Something along the lines of (with invented values for `@norm`):

```
<gram type="partOfSpeech" norm="NN">noun.simple</gram>
<gram type="partOfSpeech" norm="NN">noun.abbreviation</gram>
<gram type="partOfSpeech" norm="VV">verb.compound</gram>
<gram type="partOfSpeech" norm="AA">adverb.derivative</gram>
<gram type="partOfSpeech" norm="PP">phrase.multiWordExpression</gram>
<gram type="partOfSpeech" norm="CC">confix.partialWord</gram>
```

**Comment by anacastrosalgado** [comment]
@xlhrld This morphological information is about word structure, so I think the right place it would be in form. The lemma is an abbreviation, a simple word, a derivative, etc. And couldn't we use norm to standardize those types of lexical items?

`<form` type="lema" `norm="S">simple</form>`

**Comment by xlhrld** [comment]
The problem is that `@norm` is about the normalization of _values_ and not of _containers_. As the current guidelines state: »`@norm` gives a normalized form of information given by the source text in a non-normalized form«. Given this it is not obvious to me what `form/@norm` should actually mean. Seems like `form/@norm` should then provide a normalization of _everything_ within `form` and not just some information – in your case even information that's not recorded explicitly elsewhere. (Or is it?)

**Comment by xlhrld** [comment]
Another way to encode the morphological status would probably be to explicitly provide a morphological analysis e.g. based on `orth/w/m`. I think I recall we briefly talked about this at some point.

```
<form type="lemma">
  <orth norm="aid worker">
    <w type="multiword">
      <w type="simple">aid</w>
      <w type="simple">worker</w>
    </w>
  </orth>
</form>
```
or just:
```
<form type="lemma">
  <orth norm="aid worker">
    <w type="multiword">aid worker</w>
  </orth>
</form>
```
You can't use `orth/@type` directly because this would denote (citing the guidelines here) »… the type of spelling«.

**Comment by anacastrosalgado** [comment]
@xlhrld Thanks for your explanation. No, it isn't explicitly. I'm working on this classification.
So you recommend me use `orth/w` (word) represents a grammatical (not necessarily orthographic) word? Like this?

**decreto-lei (=decree-law)**
 `<entry` xml:id="DACL.DECRETO-LEI" xml:lang="pt">
               `<form type="lemma">
                `<orth norm="decreto-lei">
                  ### `<w type="compoud">decreto-lei</w>
                  `</orth>
`<pron>dɨkrεtulˈɐj</pron>
               `</form>
               `<gramGrp><pos>n.</pos><gen>m.</gen></gramGrp>` <---gram type?!>
               `<usg type="domain">Dir.</usg>
               `<sense xml:id="DACL.DECRETO-LEI.10">
                  `<def>Acto normativo proveniente do Governo da República.</def>
                  `<cit type="example"><quote>Actualmente, os decretos-leis são publicados na primeira série-A do <i>Diário da República</i>.</quote></cit>
               `</sense>
`<form type="inflected">
`<gramGrp> <gram type="number">Pl.</gram></gramGrp> <---something change here!>
`<orth>decretos-leis.</orth>
`</form>
`</entry>

**Comment by anacastrosalgado** [comment]
@ttasovac  do you agree?
<entry xml:lang="pt" xml:id="lexicografia">
<form type="lemma">
<orth norm="lexicografia">
<w type="simple">lexicografia</w>
</orth>
</form>

**Comment by iljackb** [comment]
Hi Ana, all,

Sorry to jump in late but I have to say that <w> is absolutely not the
right thing to use here.


*<form type="lemma"> ### <w type="compound">decreto-lei</w> *
   <pron>dɨkrεtulˈɐj</pron>

First of all if your form is orthographic, it is widely accepted that you
use <orth>, it seems that unless you are planning to use <w> instead of
<orth> on all entries, you are building a dictionary in which the same
information (ie. headwords in standard Portuguese orthography) are going to
be placed in different structures. This makes searching and extracting
unnecessarily more complicated. <w> is a corpus element and isn't for
dictionaries.

There is absolutely no reason to reinvent the wheel here. Given that your
internal entry typology is:

   - simpleWord
   - derrivativeWord
   - *compoundWord*
   - multiWordExpression
   - partialWord
   - abbreviation

*Within that typology*, the best solution is the simplest:

    <entry *type**="compoundWord"*>
       <form type="lemma">
          *<orth>decreto-lei</orth>*
          <pron>dɨkrεtulˈɐj</pron>
       </form>
       .....
    </entry>

If you declare it's a compound or multiWordExpression on entry then it
doesn't need to be repeated.

If you really want to segment the "decreto-lei" (which I see no functional
advantage of doing), there is an established practice (see: here
<https://hal.inria.fr/hal-01757108/document> and here
<https://hal.inria.fr/hal-01296498v2/document>) of using <orth><seg> for
what you have here: you can do the following:

    <entry type="compoundWord">
       <form type="lemma">
          *<orth><seg>decreto</seg><pc>-</pc><orth>*lei*</orth></orth>*
          <pron>dɨkrεtulˈɐj</pron>
       </form>
       .....
    </entry>

Also, if you are looking specifically for you Lex0 format of your internal
schema I disagree with Axel here:

You can't use orth/@type directly because this would denote (citing the
> guidelines here) »… the type of spelling«.


This is old and doesn't reflect the updated fact that <orth> has @notation
now.

So @Ana Salgado <anacastrosalgado@gmail.com> *if you are using the Lex0
typology of <entry>*, there is no reason why you can't use the following:

    <entry type="mainEntry">
       <form type="lemma">
          *<orth
type="compound"><seg>decreto</seg><pc>-</pc><orth>lei</orth></orth>*
          <pron>dɨkrεtulˈɐj</pron>
       </form>
       .....
    </entry>

@xlhrld <https://github.com/xlhrld> Going by the letter of the guidelines
in stuff like this is problematic, as we all know it is not those of use
who use most of the dictionary content who write them, those who write it
are often not informed on the usage in lexicographic practice. It really
makes no sense to replace <orth>, (which is literally one of the few
elements that pretty much any project can be expected to use) with <w>
simply because of the out of date semantics of the guidelines written by a
non-expert.

Jack

PS
@ttasovac <https://github.com/ttasovac>
I suppose I missed out in the discussion in which the Lex0 entry typology
was changed to:

   - mainEntry (default)
   - wordFamily
   - homonymicEntry
   - relatedEntry

Can you tell me what happened to having
"phrase"/"multiWordExpression"/"compound" there? That's established
practice and changing it pushes the burden downwards and leads to the need
to invent new things which is kind of counter to the mission!

**Comment by iljackb** [comment]
Sorry again, I just saw this:

represents a grammatical (not necessarily orthographic) word?
>

So even if the headwords are not all in the standard orthographic system,
as long as they aren't phonetic (i.e. what would be in <pron>) they still
should be in <orth>.

If you have a typology of these systems that you want to distinguish,
use @notation.

<orth> should be the default system for written forms which aren't
pictographic or phonetic

Best
Jack

**Comment by ambs** [comment]
I do not see the real benefit of having "decreto lei" as lemma information.

My vote would go to use something like

````
 <entry>
     <form type="lemma" type="compoundWord">
           <orth>decreto-lei</orth>
           <pron>dɨkrεtulˈɐj</pron>
     </form> ..... 
````

I am from computer sciences, and therefore I might have a biased opinion, but I think the type should be added to the form, and not to the entry. We might have two different forms, in which one is compound and the other isn't (lets imagine we can use "decreto-lei" and "decretolei" as valid).

My five cents ;)

**Comment by anacastrosalgado** [comment]
@iljackb Thanks for answering.

This solution is good:

    <entry type="compoundWord">
       <form type="lemma">
          <orth>decreto-lei</orth>
          <pron>dɨkrεtulˈɐj</pron> 
       </form>
       .....
    </entry>

or this one (@ambs ):

    '<entry>
     <form type="lemma" type="compoundWord">
           <orth>decreto-lei</orth>
           <pron>dɨkrεtulˈɐj</pron>
     </form> ..... '


Sorry, but what will be the difference by adding to the lemma or to the form? I wish to ask if there are any advantages...

**Comment by iljackb** [comment]
Hi Anna,

The second one (Suggested by Alberto) won't work because you can't have two
@type on the same element.

(There is @subtype but it is not generally used for that purpose so I
wouldn't recommend it here)

I think your entry typology is best applied to the <entry @type> itself
(this is how I do it in my projects and many others I've seen also do it).

So as mentioned, I'd recommend choosing this:

<entry type="compoundWord">
   <form type="lemma">
      <orth>decreto-lei</orth>
      <pron>dɨkrεtulˈɐj</pron>
   </form>
   .....
</entry>


Best
Jack

**Comment by ambs** [comment]
I was stupid. Yeah, we can't have two type attributes, that is correct. Sorry for missing that details.
I would still prefer to have a different key for the attribute, but let's go for the entry type for now.

Best,
Alberto

**Comment by xlhrld** [comment]
> [`orth/w`]
> […] I have to say that <w> is absolutely not the right thing to use here. […]

@iljackb is right here, `w` was too fast a shot from my side, `seg` could be the better option.

However,

> There is absolutely no reason to reinvent the wheel here. Given that your internal entry typology is: - simpleWord - derrivativeWord - *compoundWord* - multiWordExpression - partialWord - abbreviation *Within that typology*, the best solution is the simplest: <entry *type**="compoundWord"*>

that may be the simplest solution but in TEI Lex-0 we want to do better, actually. The core problem with this conception of `entry/@type` is, that it reflects **morphological** information:

Firstly, I see no apparent reason why morphological information is so special it should be attached to the top most element of a lexical entry. This seems very arbitrary to me.

Secondly, with morphological information attached to the logical root node we restrain ourselves to **one** single value for it. This doesn't work unless we allow _lists of types_ for dictionaries that happen to provide competing morphological analyses for a given headword. At least in German it is often difficult to decide whether a headword is a compound or a derivative for words with verbal roots and certain affixoids. For these, you will encounter statements along the lines of »either compound … or derivative«. You wouldn't want to introduce `entry/@type="compoundWord_or_derivativeWord"` or `entry/@type="compoundWord derivativeWord"`, do you?

Thirdly, we would rather want a complex description of the morphological status of a headword anyway and not just the type of the morphological process. One obvious example would be the  (immediate) constituents the process works on. We need a structured representation for morphological information and _this_ should get the morphological `@type`.

**Comment by ttasovac** [comment]
A question from @kdepuydt  this morning made me realize that this ticket was still open even though our "vertical" typology, agreed upon in a f2f meeting in Berlin a long, long time ago is very stable. 

At the moment, we recommend but do not require the use of our typology, and we have a Schematron rule that signals the presence of typeless nested entries —  as an encouragement to our users. 

"Horizontal" typologies (for instance, those based on morphological criteria) should be encoded using other mechanisms.

We have examples in the Guidelines of word families as well (from Arabic dictionaries, courtesy of @MedKhem). See, for instance, Section 2.2.4 on the deprecation of superEntry.

If there are any specific questions or comments, please open a new ticket.
