### ISSUE TITLE
TEI Lex-0 question (rng) generation

### ISSUE THREAD

**Issue by eduarddrenth** [DARIAH-ERIC/lexicalresources#144]
The provided rng, is it generated from odd or compiled odd?

Is generation integrated in the build process and based on fixed version of TEI stylesheets?

**Comment by ttasovac** [comment]
The RNG is generated from ODD via a set of stylesheets using xProc (see https://github.com/DARIAH-ERIC/lexicalresources/blob/master/Schemas/TEILex0/xproc/teilex0.xpl). We also use a hack to strip our examples of namespaces so that they can be included in the ODD file as <egXML>: see https://dariah-eric.github.io/lexicalresources/pages/TEILex0/TEILex0.html#index.xml-body.1_div.12_div.3_div.1 and https://github.com/BCDH/tei-strip-and-include. 

We don't use a fixed version of TEI stylesheets but build against the latest version.

Finally, no, the generation is not integrated in the build process although I wish it had been.  I never found the time to learn how to do it. It would be ideal if we used some kind of CI like GitHub Actions where we commit the ODD file to GitHub and the rest happens automatically.

**Comment by eduarddrenth** [comment]
Here you find a maven based build process compiling odd, generating xsd, rng and schematron: https://bitbucket.org/fryske-akademy/online-dictionaries/raw/7ea9156c5c1c09cca19cfdedd434d95b1ac05fd6/pom.xml

Here you find slides on odd explaining this: https://drive.google.com/file/d/1dpmdIuBFqiEFj6sNneF-x-9X4aDkd5Ad/view?usp=sharing and pres: https://youtu.be/Ef-bkXsIvB4.

I am going to integrate Lex-0 validation and transformation in the next version of https://search.maven.org/search?q=a:teidictionaries, based on this build pipeline and your Lex-0 odd

**Comment by ttasovac** [comment]
Thanks, I'll take a look —  although I don't really know Maven. If I find the time to experiment with it, I may get back to you for some advice. 

It will be really cool if you automate the validation of your dictionaries by compiling RNG directly from our odd. 

I will close this issue now, but feel free to come back to it if you have any additional questions.
