### ISSUE TITLE
<editorialDecl> element should contain more then <p> element

### ISSUE THREAD

**Issue by daliboris** [DARIAH-ERIC/lexicalresources#156]
There is an item in the 2.1 section of TEI Lex-0 Guidelines:

> an encoding description, tagged [encodingDesc](https://dariah-eric.github.io/lexicalresources/pages/TEILex0/spec.html#TEI.encodingDesc), describes the relationship between the electronic resource and its source(s). It allows for detailed description of whether (or how) the electronic resource was produced, **transcribed** or **normalized**, how the encoder resolved **ambiguities** in the source, what levels of **encoding** or **analysis** were applied etc.

But `<editorialDecl>` element in TEI Lex-0  can now contain only `<p>` elements. For more precise description other elements would be appropriate, as in full TEI Guidelines:  `<correction>`, `<hyphenation>`, `<interpretation>`, `<normalization>`, `<punctuation>`, `<quotation>`, `<segmentation>`, `<stdVals>`.

Content model for `<editorialDecl>` refers to `<classRef key="model.editorialDeclPart"/>` (see [12.1.30.](https://dariah-eric.github.io/lexicalresources/pages/TEILex0/spec.html#TEI.editorialDecl)), but this model is not allowed (in RNG):

```xml
<define name="model.editorialDeclPart">
 <notAllowed/>
</define>
```

There are also examples  (see [12.1.30.](https://dariah-eric.github.io/lexicalresources/pages/TEILex0/spec.html#TEI.editorialDecl)) with `<normalization>` and `<quotation>` elements, which aren't allowed by current RNG schema.

**Comment by ttasovac** [comment]
The examples you mention come in fact from the general TEI Guidelines —  they are picked up when we create our Guidelines because we're using TEI-C Stylesheets to do most of the heavy lifting in creating the documentation from the odd file. We could probably override them somehow, but nobody will have the time to do that any time soon. 

I wouldn't want to simply allow everything that comes from TEI in `editorialDecl` before having a proper discussion about what they are and whether they are actually useful in dictionary projects.

I'll be happy to hear about your (plural) experiences, how you have or how you would want to use these elements. Real, not made-up examples, would be great.

**Comment by ttasovac** [comment]
@daliboris by the way, I find this super important —  especially considering your ongoing work with TEI Publisher and making the TEI Header really robust for dictionaries published with TEI Publisher. There are other areas in which TEI Header will be very important, but I can tell you about it more when we speak...

**Comment by ttasovac** [comment]
Agreed to leave things as they are. We will reopen the issue if we get concrete implementations that don't work with simple paragraphs. There was a long discussion about this during the Lexicographic Resources Summit 2023.
