### ISSUE TITLE
Desperately seeking example for ref/@notation

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/lexicalresources#18]
We propose `ref/@notation`

> to indicate, like we currently do on `<orth>` or `<pron>`, the actual notation used for the explicit lexical form when provided

Could somebody provide a real-life example or two for this?

Also, we had a note that a ticket should be submitted to make `ref` member of `att.notated`. Let's look at the examples first. If there is consensus, we can pursue a ticket for the Council.

**Comment by ttasovac** [comment]
@iljackb do you have an example of this? @laurentromary thought you may use something like this.

**Comment by iljackb** [comment]
So I assume this is instead of <pRef> and <oRef>.

Given that <pRef> is a reference version of <pron>, which of course needs
to be able to have the notation specified, in a project in which you have
multiple notations which can happen if you are using content from different
sources (e.g. in our Bavarian data we have the notation teutonista which
was used before ipa was around) you have <pRef notation="ipa"> or <pRef
notation="teutonista">.

This could also be used with <oRef> if for example you have Japanese in
which there are multiple alphabets/syllabaries you could use @notation on
<oRef>, e.g. <oRef notation="hiragana">, <oRef notation="katakana">, <oRef
notation="kanji">

Thus, since you are generalizing the different types of o/p Refs to <ref>,
the use of @notation would be used along the same lines for the same
purposes.

Best
Jack

**Comment by ttasovac** [comment]
Hi @iljackb!

I understand why we need this, but I would like to have a concrete example for the guidelines. Would you be able to dig up an example from your Bavarian dictionary of a cross-reference using the teutonista notation?

**Comment by ttasovac** [comment]
Feel free to reopen with actual examples...
