### ISSUE TITLE
Do we need ref/@type?

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/lexicalresources#20]
Currently we have:

> `ref/@type` may be an indication of the target object category (entry, sense, ….)

and this example

```xml
<entry>
   <form type="lemma">
      <orth>dog</orth>
   </form>
   <sense>
      <xr type="hyperonym">
         <ref xml:lang="en" type="entry">mammal</ref>
      </xr>
   </sense>
</entry>
```

I'm not sure it's very useful to have this attribute. In real-life examples, we would target the xml:id of either an entry or a sense. Also, in the narrative section, we say that `ref/@type` _may_ be an indication... which is very non-committal. 

So, I'd like to get rid of this, but I do need a second opinion.

**Comment by ttasovac** [comment]
Laurent likes this, we're keeping it. We'll create a semi-closed list of values for it.

**Comment by ttasovac** [comment]
@laurentromary could you please add a semi-closed list of values ("entry", "sense") to `ref/@type`

**Comment by xlhrld** [comment]
@laurentromary Could you possibly tell us **why** you like `ref/@type`? If there is `ref/@target` we can simply go to that target and determine its type first-hand. No need to duplicate this information, I'd say. But I may be missing the point here, of course …

In any case: The set {`entry`, `sense`} seems strange; I'd expect something like {`entry`, `form`, `sense`} at least.

**Comment by iljackb** [comment]
I also think make it _required_ rather than _suggested_ is maybe not the best choice.

I could envision needing to add `<ref @type>` to a dataset that doesn't have it already could be a burden and a problem to potential users, likely requiring them to do more work than just convert an existing dataset (automatically or manually) into a parallel structure.

 Specifically, it could require that they add more categorization than needed, and if there is no pre-existing information that would help automate the additional need of choosing & adding `@type` on `<ref>` (e.g. while you can automatically assume that where you have `<xr type="synonym">`, the attribute value of `<ref @type>` will be "sense", you couldn't necessarily assume that for something more generic where just a form is listed which would be a reference to an entry as a whole or to the form...)

So I'm in favor of `suggesting` it and trying to create a list of suggested possible values. However other that those listed by @xlhrld ({entry, form, sense}) I can think of any others at this point.

PS. Just as I was writing this, serendipitously Ana (with the Portuguese Academy Dictionary who is converting the previous edition into TEI-Lex0), literally just came in and asked me why the schema is making her put `@type` on `<xr><ref>` her in data!

**Comment by kdepuydt** [comment]
it may be useful where there is no identified target, so it cannot be directly determined from the reference)

**Comment by ttasovac** [comment]
@laurentromary and @ttasovac will look at this next time, when we're not so tired.

**Comment by xlhrld** [comment]
There should be at least a clear distribution of labour between `xr/@type` and `ref/@type`. Maybe along the lines of:
- `xr/@type` for the type of relation (lexical, or a specific lexical-semantic relation type vs. e. g. bibliographical)
- `ref/@type` (optional) for the type of the entity that's pointed to (e. g. _entry_, _sense_, …, even _bibl_ maybe?).

In this scheme, I don't see an obvious default for `ref/@type` because the default depends on the type of the dictionary. In etymological dictionaries you would typically reference entries whereas in semasiological dictionaries it is at least equally common to point to distinct senses. _lexical_ as default for `xr/@type` seems reasonable, though.

**Comment by laurentromary** [comment]
Yes, I think we agreed on this distinction. A possible default could be "lexicalObject" or something equivalent. I would be very reluctant to leave `<ref>` untyped when it can be mixed up with other usage (such as bibliographic). I must say that looking at the TEI guidelines, there should probably be more done on the semantics of `<ref>`, but that's another story.
