### ISSUE TITLE
xr/@type="lexical" vs. xr/@type="cf"

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/lexicalresources#21]
I don't understand the distinction between `xr/@type="lexical"` (which we say is the default value of the type attribute) and `xr/@type="cf"`which we say is used for untyped cross-references.

**Comment by xlhrld** [comment]
In general, we try to use explicit vocabulary for attributes. So here, instead of `"cf"` we should have `"untyped"` for, well, untyped `xr`. Like @ttasovac, I don't immediately see the application for `"lexical"` as a value for `xr/@type`, let alone as a default. If we know something is a lexical link we should be able to specify this type (e.g. as being one of the lexical-semantic types). If not, how do we know its a »lexical« `xr` in the first place?

**Comment by ttasovac** [comment]
Lauren and I agreed to call the default relation "related" —  i.e. `<xr type='related'>`. Other values we allow there are synonymy, antonymy etc. All this is in the schema. But @ttasovac should fix the documentation as well!!!!

**Comment by laurentromary** [comment]
`<quote>`@ttasovac should fix the documentation as well!`</quote>`

**Comment by kdepuydt** [comment]
I do not understand "lexical"

**Comment by ttasovac** [comment]
Closing this because `<xr type="lexical">` is no longer valid.
